# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7b9a25b67760b86de808ef7c63f6c9d37869637db26667720d2efe2cfa72a1d1f2ba17ccd2322c733dbed4a0bbaa1dc4f7fcd18bedd8dcd87718d16eaad761bb

test:
  secret_key_base: eda8d5be5b957783d6cd79880af71ee5a4681857c8c059d20e56d07367b31dcb147d0fabf9ab8b373973089682ee15c3c0b7d6335a1276ef11e051c420d4c2d4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
